# Generated by Django 4.1.3 on 2023-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
